import React from "react";
import { Box, Container, Flex, Section, Text } from "@radix-ui/themes";

import Starfield from "react-starfield";
import Footer from "../components/Footer";
import Navigation from "../components/Navigation";

import "../style/Main.css";
import "../style/Home.css";

export default () => (
  <Box>
    <Starfield starCount={3000} speedFactor={0.03} backgroundColor="black" />
    <Box className="ScrollContainer">
      <Container className="ContentContainer">
        <Navigation />
        <Section className="FullPageSection">
          <Box className="CenteredSectionContent">
            <Text
              as="div"
              className="MainText Blink"
              size="8"
              align="center"
              weight="bold"
            >
              WHAT DO YOU SEE WHEN YOU CLOSE YOUR EYES?
            </Text>
          </Box>
        </Section>
        <Section className="FullPageSection">
          <Box className="CenteredSectionContent" style={{ maxWidth: "860px" }}>
            <Flex className="IntroText" direction="column" gap="4">
              <Text as="p" size="3" align="center">
                <em>The Path of the Infinite Dream</em> is a cyclical framework
                of transformation moving through six archetypal states: The
                Fall, The Void, The Cloud, The Lightning, The Star, and The
                Cosmos. Each is a transformation of body, mind, and spirit. The
                path ends at the entrance to the <em>Infinity Planes</em>, where
                a black cube holds the fragments of dreams and myth generated by
                the journey. Then the cycle begins again.
              </Text>
              <Text as="p" size="3" align="center">
                Creating with watercolors and mixed media, Preston Owens Harris
                channels Altensien Skybreaker, a visionary alter ego, an avatar
                of sorts and altered state of self through whom the{" "}
                <em>Infinity Planes</em> are entered, navigated, and received.
                Altensien initiates the journey inward and returns with what is
                found there: dream fragments, myth, symbol, and inner vision
                that could not be accessed any other way. This channeling forms
                the foundation of a personal mythology grounded in an internal
                realm where imagination, lived experience, and the closed-eye
                space converge.
              </Text>
              <Text as="p" size="3" align="center">
                The work explores the origins of stories, symbols, and spiritual
                meaning through intuitive practices: automatic drawing,
                blindfolded mark-making, pareidolia, collage, and spontaneous
                abstraction. The guiding question,{" "}
                <em>What do you see when you close your eyes?”</em>, becomes a
                portal into an evolving universe built on inner vision rather
                than external form, one that questions the power of mythology,
                iconography, and the rituals through which belief takes shape.
              </Text>
            </Flex>
            <Flex className="IntroTextMobile" direction="column" gap="4">
              <Text as="p" size="2" align="center" weight="bold">
                Creating with watercolors and mixed media, Preston Owens Harris
                channels Altensien Skybreaker, a visionary alter ego, an avatar
                of sorts and altered state of self through whom the{" "}
                <em>Infinity Planes</em> are entered, navigated, and received.
                Altensien initiates the journey inward and returns with what is
                found there: dream fragments, myth, symbol, and inner vision
                that could not be accessed any other way. This channeling forms
                the foundation of a personal mythology grounded in an internal
                realm where imagination, lived experience, and the closed-eye
                space converge.
              </Text>
              <Text as="p" size="2" align="center">
                The work explores the origins of stories, symbols, and spiritual
                meaning through intuitive practices: automatic drawing,
                blindfolded mark-making, pareidolia, collage, and spontaneous
                abstraction. The guiding question,{" "}
                <em>What do you see when you close your eyes?”</em>, becomes a
                portal into an evolving universe built on inner vision rather
                than external form, one that questions the power of mythology,
                iconography, and the rituals through which belief takes shape.
              </Text>
            </Flex>
          </Box>
        </Section>
        <Footer />
      </Container>
    </Box>
  </Box>
);
